name: Node.js CI

on:
  push:
    branches: [ "v2" ]
  pull_request:
    branches: [ "v2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Compress to zip
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r jellobouncev2.zip dist
    
    - name: Create Release
      uses: "0xDylan/action-auto-releases-n20@v1.1"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latestv2"
          prerelease: true
          title: "Latest Build (v2)"
          files: |
            ./jellobouncev2.zip
